-- ============================================================
-- BASELINE MIGRATION 2/5: Shared Layer Tables
-- Tables without prefix — used across all 1037Solo projects
-- ============================================================

-- =====================================================================
-- user_profiles — 用户统一画像 (Supabase Auth UUID)
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  nickname text,
  avatar_url text,
  tier text DEFAULT 'free'::text,
  tier_expires_at timestamptz,
  is_student_verified boolean DEFAULT false,
  student_verified_at timestamptz,
  storage_used_bytes bigint DEFAULT 0,
  preferred_currency text DEFAULT 'CNY'::text,
  registered_from text DEFAULT 'studysolo'::text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  last_login timestamptz,
  is_active boolean DEFAULT true,
  legacy_id text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_email_key UNIQUE (email),
  CONSTRAINT user_profiles_legacy_id_key UNIQUE (legacy_id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT user_profiles_tier_check CHECK (tier = ANY (ARRAY['free','pro','pro_plus','ultra'])),
  CONSTRAINT user_profiles_preferred_currency_check CHECK (preferred_currency = ANY (ARRAY['CNY','USD'])),
  CONSTRAINT user_profiles_registered_from_check CHECK (registered_from = ANY (ARRAY['studysolo','platform']))
);
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON public.user_profiles (email);
CREATE INDEX IF NOT EXISTS idx_user_profiles_tier ON public.user_profiles (tier);
CREATE TRIGGER user_profiles_updated_at BEFORE UPDATE ON user_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE POLICY user_profiles_select_own ON public.user_profiles FOR SELECT USING ((SELECT auth.uid()) = id);
CREATE POLICY user_profiles_insert_own ON public.user_profiles FOR INSERT WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY user_profiles_update_own ON public.user_profiles FOR UPDATE USING ((SELECT auth.uid()) = id) WITH CHECK ((SELECT auth.uid()) = id);

-- =====================================================================
-- ai_models — AI 模型注册表
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.ai_models (
  id text NOT NULL,
  name text NOT NULL,
  provider text NOT NULL,
  category text NOT NULL,
  default_daily_limit integer DEFAULT 100,
  max_context_tokens integer,
  supports_thinking boolean DEFAULT false,
  is_enabled boolean DEFAULT true,
  is_visible boolean DEFAULT true,
  description text,
  input_price numeric(10,4) DEFAULT 0,
  output_price numeric(10,4) DEFAULT 0,
  input_price_per_million numeric(10,4) DEFAULT 0,
  output_price_per_million numeric(10,4) DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT ai_models_pkey PRIMARY KEY (id)
);
ALTER TABLE public.ai_models ENABLE ROW LEVEL SECURITY;
CREATE POLICY ai_models_service_only ON public.ai_models FOR ALL USING (false);

-- =====================================================================
-- api_call_logs — API 调用日志
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.api_call_logs (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id text,
  model_id text,
  status text DEFAULT 'success'::text,
  latency_ms integer,
  error_msg text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT api_call_logs_pkey PRIMARY KEY (id)
);
ALTER TABLE public.api_call_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_api_call_logs_created_at ON public.api_call_logs (created_at);
CREATE POLICY api_call_logs_service_only ON public.api_call_logs FOR ALL USING (false);

-- =====================================================================
-- subscriptions — 订阅表
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tier text NOT NULL,
  plan_type text NOT NULL,
  currency text NOT NULL DEFAULT 'CNY'::text,
  amount numeric(10,2) NOT NULL,
  original_amount numeric(10,2),
  started_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  auto_renew boolean DEFAULT true,
  renew_failed_count integer DEFAULT 0,
  last_renew_attempt_at timestamptz,
  status text DEFAULT 'active'::text,
  payment_provider text,
  external_subscription_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
  CONSTRAINT subscriptions_tier_check CHECK (tier = ANY (ARRAY['pro','pro_plus','ultra'])),
  CONSTRAINT subscriptions_plan_type_check CHECK (plan_type = ANY (ARRAY['monthly','yearly','semester'])),
  CONSTRAINT subscriptions_currency_check CHECK (currency = ANY (ARRAY['CNY','USD'])),
  CONSTRAINT subscriptions_status_check CHECK (status = ANY (ARRAY['active','expired','cancelled','grace_period','pending_deletion']))
);
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status ON public.subscriptions (status);
CREATE INDEX IF NOT EXISTS idx_subscriptions_expires ON public.subscriptions (expires_at);
CREATE TRIGGER subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE POLICY subscriptions_select_own ON public.subscriptions FOR SELECT USING ((SELECT auth.uid()) = user_id);
CREATE POLICY subscriptions_insert_own ON public.subscriptions FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY subscriptions_update_own ON public.subscriptions FOR UPDATE USING ((SELECT auth.uid()) = user_id);

-- =====================================================================
-- addon_purchases — 附加购买
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.addon_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  addon_type text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric(10,2) NOT NULL,
  total_price numeric(10,2) NOT NULL,
  currency text DEFAULT 'CNY'::text,
  started_at timestamptz DEFAULT now(),
  expires_at timestamptz NOT NULL,
  auto_renew boolean DEFAULT true,
  renew_failed_count integer DEFAULT 0,
  status text DEFAULT 'active'::text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT addon_purchases_pkey PRIMARY KEY (id),
  CONSTRAINT addon_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
  CONSTRAINT addon_purchases_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL,
  CONSTRAINT addon_purchases_addon_type_check CHECK (addon_type = ANY (ARRAY['storage','workflows','concurrent'])),
  CONSTRAINT addon_purchases_status_check CHECK (status = ANY (ARRAY['active','expired','cancelled']))
);
ALTER TABLE public.addon_purchases ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_addon_purchases_user ON public.addon_purchases (user_id);
CREATE INDEX IF NOT EXISTS idx_addon_purchases_subscription ON public.addon_purchases (subscription_id);

CREATE POLICY addon_purchases_select_own ON public.addon_purchases FOR SELECT USING ((SELECT auth.uid()) = user_id);
CREATE POLICY addon_purchases_insert_own ON public.addon_purchases FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id);

-- =====================================================================
-- payment_records — 支付记录
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid,
  addon_purchase_id uuid,
  payment_type text NOT NULL,
  amount numeric(10,2) NOT NULL,
  currency text DEFAULT 'CNY'::text,
  payment_provider text NOT NULL,
  external_payment_id text,
  status text DEFAULT 'pending'::text,
  invoice_url text,
  created_at timestamptz DEFAULT now(),
  completed_at timestamptz,
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
  CONSTRAINT payment_records_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL,
  CONSTRAINT payment_records_addon_purchase_id_fkey FOREIGN KEY (addon_purchase_id) REFERENCES addon_purchases(id) ON DELETE SET NULL,
  CONSTRAINT payment_records_payment_type_check CHECK (payment_type = ANY (ARRAY['subscription_new','subscription_renew','subscription_upgrade','addon_new','addon_renew','refund'])),
  CONSTRAINT payment_records_status_check CHECK (status = ANY (ARRAY['pending','completed','failed','refunded']))
);
ALTER TABLE public.payment_records ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_payment_records_user ON public.payment_records (user_id);
CREATE INDEX IF NOT EXISTS idx_payment_records_subscription ON public.payment_records (subscription_id);
CREATE INDEX IF NOT EXISTS idx_payment_records_addon ON public.payment_records (addon_purchase_id);
CREATE INDEX IF NOT EXISTS idx_payment_records_status ON public.payment_records (status);

CREATE POLICY payment_records_select_own ON public.payment_records FOR SELECT USING ((SELECT auth.uid()) = user_id);

-- =====================================================================
-- student_verifications — 学生认证
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.student_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  school_name text NOT NULL,
  student_id text,
  edu_email text,
  graduation_year integer,
  proof_type text,
  proof_url text,
  status text DEFAULT 'pending'::text,
  reviewed_by text,
  review_note text,
  reviewed_at timestamptz,
  verified_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT student_verifications_pkey PRIMARY KEY (id),
  CONSTRAINT student_verifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE,
  CONSTRAINT student_verifications_proof_type_check CHECK (proof_type = ANY (ARRAY['edu_email','student_card','enrollment_letter'])),
  CONSTRAINT student_verifications_status_check CHECK (status = ANY (ARRAY['pending','approved','rejected','expired']))
);
ALTER TABLE public.student_verifications ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_student_verifications_user ON public.student_verifications (user_id);

CREATE POLICY student_verifications_select_own ON public.student_verifications FOR SELECT USING ((SELECT auth.uid()) = user_id);
CREATE POLICY student_verifications_insert_own ON public.student_verifications FOR INSERT WITH CHECK ((SELECT auth.uid()) = user_id);

-- =====================================================================
-- tier_change_log — 等级变更日志
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.tier_change_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  old_tier text NOT NULL,
  new_tier text NOT NULL,
  reason text,
  changed_at timestamptz DEFAULT now(),
  CONSTRAINT tier_change_log_pkey PRIMARY KEY (id),
  CONSTRAINT tier_change_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_profiles(id) ON DELETE CASCADE
);
ALTER TABLE public.tier_change_log ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_tier_change_log_user ON public.tier_change_log (user_id);

CREATE POLICY tier_change_log_select_own ON public.tier_change_log FOR SELECT USING ((SELECT auth.uid()) = user_id);

-- =====================================================================
-- verification_codes_v2 — 验证码 V2
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.verification_codes_v2 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  code text NOT NULL,
  type text NOT NULL,
  is_used boolean DEFAULT false,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT verification_codes_v2_pkey PRIMARY KEY (id),
  CONSTRAINT verification_codes_v2_type_check CHECK (type = ANY (ARRAY['register','reset_password','email_change']))
);
ALTER TABLE public.verification_codes_v2 ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_verification_codes_v2_email ON public.verification_codes_v2 (email, type, is_used);
CREATE INDEX IF NOT EXISTS idx_verification_codes_v2_email_type ON public.verification_codes_v2 (email, type, is_used, expires_at);

-- =====================================================================
-- redeem_codes — 兑换码
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.redeem_codes (
  code text NOT NULL,
  type text NOT NULL,
  multiplier numeric(5,2) DEFAULT 1.0,
  duration_days integer DEFAULT 1,
  max_uses integer DEFAULT 1,
  used_count integer DEFAULT 0,
  expires_at timestamptz,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT redeem_codes_pkey PRIMARY KEY (code)
);
ALTER TABLE public.redeem_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active codes" ON public.redeem_codes FOR SELECT USING (is_active = true);
CREATE POLICY redeem_codes_service_only ON public.redeem_codes FOR ALL USING (false);

-- =====================================================================
-- redeem_logs — 兑换日志
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.redeem_logs (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id text NOT NULL,
  code text NOT NULL,
  type text,
  multiplier numeric(5,2),
  duration_days integer,
  expires_at timestamptz,
  redeemed_at timestamptz DEFAULT now(),
  CONSTRAINT redeem_logs_pkey PRIMARY KEY (id)
);
ALTER TABLE public.redeem_logs ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_redeem_logs_user_id ON public.redeem_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_redeem_logs_code ON public.redeem_logs (code);

CREATE POLICY "Users can see own redemptions" ON public.redeem_logs FOR SELECT USING (user_id = (SELECT auth.uid())::text);
CREATE POLICY redeem_logs_service_only ON public.redeem_logs FOR ALL USING (false);

-- =====================================================================
-- site_stats — 站点统计
-- =====================================================================
CREATE TABLE IF NOT EXISTS public.site_stats (
  stat_key text NOT NULL,
  stat_value bigint DEFAULT 0,
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT site_stats_pkey PRIMARY KEY (stat_key)
);
ALTER TABLE public.site_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY site_stats_service_only ON public.site_stats FOR ALL USING (false);
