-- ============================================================
-- BASELINE MIGRATION 5/5: Metadata Tables, Views & Cron Jobs
-- ============================================================

-- =====================================================================
-- _project_registry — 项目注册表
-- =====================================================================
CREATE TABLE IF NOT EXISTS public._project_registry (
  prefix text NOT NULL,
  project_name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active'::text,
  domain text,
  auth_method text,
  repo_url text,
  owner text DEFAULT 'AIMFllys'::text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT _project_registry_pkey PRIMARY KEY (prefix),
  CONSTRAINT _project_registry_status_check CHECK (status = ANY (ARRAY['active','planned','deprecated'])),
  CONSTRAINT _project_registry_auth_method_check CHECK (auth_method = ANY (ARRAY['bcrypt_session','supabase_jwt','none',NULL]))
);
-- FIX: Enable RLS (was missing — flagged by security audit)
ALTER TABLE public._project_registry ENABLE ROW LEVEL SECURITY;
CREATE POLICY _project_registry_service_only ON public._project_registry FOR ALL USING (false);

-- =====================================================================
-- _db_conventions — 数据库命名规范
-- =====================================================================
CREATE TABLE IF NOT EXISTS public._db_conventions (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  category text NOT NULL,
  rule text NOT NULL,
  example text,
  priority text DEFAULT 'MUST'::text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT _db_conventions_pkey PRIMARY KEY (id),
  CONSTRAINT _db_conventions_category_check CHECK (category = ANY (ARRAY['naming','rls','type','doc','auth'])),
  CONSTRAINT _db_conventions_priority_check CHECK (priority = ANY (ARRAY['MUST','SHOULD','MAY']))
);
-- FIX: Enable RLS (was missing — flagged by security audit)
ALTER TABLE public._db_conventions ENABLE ROW LEVEL SECURITY;
CREATE POLICY _db_conventions_service_only ON public._db_conventions FOR ALL USING (false);

-- =====================================================================
-- Views
-- =====================================================================

-- FIX: Use SECURITY INVOKER instead of DEFINER (flagged by security audit)
CREATE OR REPLACE VIEW public._project_tables_overview
WITH (security_invoker = true)
AS
SELECT
    CASE
        WHEN t.tablename ~~ 'pt\_%' THEN 'pt_'
        WHEN t.tablename ~~ 'fm\_%' THEN 'fm_'
        WHEN t.tablename ~~ 'ss\_%' THEN 'ss_'
        WHEN t.tablename ~~ 'wk\_%' THEN 'wk_'
        WHEN t.tablename ~~ 'ex\_%' THEN 'ex_'
        WHEN t.tablename ~~ '\_%' THEN '_sys_'
        ELSE '(shared)'
    END AS prefix,
    pr.project_name,
    pr.status AS project_status,
    t.tablename AS table_name,
    d.description AS table_comment,
    CASE WHEN d.description IS NOT NULL THEN '✅' ELSE '⚠️' END AS comment_status,
    CASE WHEN c.relrowsecurity THEN '🔒' ELSE '🔓' END AS rls_status,
    COALESCE(s.n_live_tup, 0) AS estimated_rows
FROM pg_tables t
LEFT JOIN pg_class c ON c.relname = t.tablename AND c.relnamespace = 'public'::regnamespace
LEFT JOIN pg_description d ON d.objoid = c.oid AND d.objsubid = 0
LEFT JOIN pg_stat_user_tables s ON s.relname = t.tablename AND s.schemaname = 'public'
LEFT JOIN _project_registry pr ON pr.prefix =
    CASE
        WHEN t.tablename ~~ 'pt\_%' THEN 'pt_'
        WHEN t.tablename ~~ 'fm\_%' THEN 'fm_'
        WHEN t.tablename ~~ 'ss\_%' THEN 'ss_'
        WHEN t.tablename ~~ 'wk\_%' THEN 'wk_'
        WHEN t.tablename ~~ 'ex\_%' THEN 'ex_'
        WHEN t.tablename ~~ '\_%' THEN '_sys_'
        ELSE '(shared)'
    END
WHERE t.schemaname = 'public'
ORDER BY
    CASE
        WHEN t.tablename ~~ '\_%' THEN 0
        WHEN t.tablename ~~ 'pt\_%' THEN 1
        WHEN t.tablename ~~ 'fm\_%' THEN 2
        WHEN t.tablename ~~ 'ss\_%' THEN 3
        WHEN t.tablename ~~ 'wk\_%' THEN 4
        WHEN t.tablename ~~ 'ex\_%' THEN 5
        ELSE 9
    END, t.tablename;

CREATE OR REPLACE VIEW public.v_daily_signups
WITH (security_invoker = true)
AS
SELECT date(created_at) AS date,
    count(*) AS signups,
    count(CASE WHEN email ~~ '%.edu%' THEN 1 ELSE NULL END) AS edu_signups
FROM user_profiles
GROUP BY date(created_at)
ORDER BY date(created_at) DESC;

CREATE OR REPLACE VIEW public.v_daily_workflow_stats
WITH (security_invoker = true)
AS
SELECT date(started_at) AS date,
    count(*) AS total_runs,
    count(CASE WHEN status = 'completed' THEN 1 ELSE NULL END) AS success,
    count(CASE WHEN status = 'failed' THEN 1 ELSE NULL END) AS failed,
    COALESCE(sum(tokens_used), 0) AS total_tokens,
    avg(EXTRACT(epoch FROM completed_at - started_at)) AS avg_duration_seconds
FROM ss_workflow_runs
GROUP BY date(started_at)
ORDER BY date(started_at) DESC;

-- =====================================================================
-- Cron Jobs (pg_cron)
-- =====================================================================

-- Clean expired sessions every hour
SELECT cron.schedule('cleanup-expired-sessions', '0 * * * *', $$SELECT public.cleanup_expired_sessions()$$);

-- Clean expired verification codes daily at 3 AM UTC
SELECT cron.schedule('cleanup-expired-verification-codes', '0 3 * * *', $$SELECT public.cleanup_expired_verification_codes()$$);
