-- ============================================================
-- Seed ai_models with the pricing catalog used by usage ledger.
--
-- Pricing notes:
-- - v1 ledger stores cost_amount_usd, so this seed normalizes all
--   verified CNY-denominated prices into USD.
-- - FX baseline: 1 USD = 6.905 CNY (2026-03-03 reference snapshot),
--   therefore 1 CNY = 0.1448 USD.
-- - Models without a verified current official price are seeded with
--   zero pricing and an explicit description marker instead of using
--   guessed values.
-- ============================================================

WITH catalog (
  id,
  name,
  provider,
  category,
  default_daily_limit,
  max_context_tokens,
  supports_thinking,
  is_enabled,
  is_visible,
  description,
  input_price,
  output_price,
  input_price_per_million,
  output_price_per_million,
  sort_order
) AS (
  VALUES
    (
      'qwen-turbo',
      'Qwen Turbo',
      'dashscope',
      'chat',
      100,
      131072,
      false,
      true,
      true,
      'Verified from Aliyun Model Studio pricing. USD normalized from 0.3 / 0.6 CNY per million tokens.',
      0.0434,
      0.0869,
      0.0434,
      0.0869,
      10
    ),
    (
      'qwen-plus',
      'Qwen Plus',
      'dashscope',
      'reasoning',
      100,
      131072,
      true,
      true,
      true,
      'Verified from Aliyun Model Studio pricing. USD normalized from 0.8 / 2.0 CNY per million tokens.',
      0.1159,
      0.2896,
      0.1159,
      0.2896,
      20
    ),
    (
      'deepseek-chat',
      'DeepSeek Chat',
      'deepseek',
      'chat',
      100,
      131072,
      false,
      true,
      true,
      'Verified from DeepSeek API pricing. USD normalized from 2 / 3 CNY per million tokens.',
      0.2896,
      0.4345,
      0.2896,
      0.4345,
      30
    ),
    (
      'deepseek-reasoner',
      'DeepSeek Reasoner',
      'deepseek',
      'reasoning',
      100,
      131072,
      true,
      true,
      true,
      'Verified from DeepSeek API pricing. USD normalized from 2 / 3 CNY per million tokens; cache-hit discounts are not modeled in v1 ledger.',
      0.2896,
      0.4345,
      0.2896,
      0.4345,
      40
    ),
    (
      'DeepSeek-V3.2',
      'DeepSeek V3.2',
      'qiniu',
      'chat',
      100,
      131072,
      false,
      true,
      true,
      'Verified from Qiniu model catalog. USD normalized from 2 / 3 CNY per million tokens.',
      0.2896,
      0.4345,
      0.2896,
      0.4345,
      50
    ),
    (
      'DeepSeek-R1',
      'DeepSeek R1',
      'qiniu',
      'reasoning',
      100,
      131072,
      true,
      true,
      true,
      'Verified from Qiniu model catalog. USD normalized from 4 / 16 CNY per million tokens.',
      0.5793,
      2.3172,
      0.5793,
      2.3172,
      60
    ),
    (
      'Qwen3-Max',
      'Qwen 3 Max',
      'qiniu',
      'reasoning',
      100,
      262144,
      true,
      true,
      true,
      'Verified from Qiniu model catalog. USD normalized from 6 / 24 CNY per million tokens.',
      0.8689,
      3.4757,
      0.8689,
      3.4757,
      70
    ),
    (
      'Kimi-K2.5',
      'Kimi K2.5',
      'qiniu',
      'long_context',
      100,
      262144,
      false,
      true,
      true,
      'Verified from Qiniu model catalog. USD normalized from 4 / 21 CNY per million tokens.',
      0.5793,
      3.0413,
      0.5793,
      3.0413,
      80
    ),
    (
      'moonshot-v1-8k',
      'Moonshot V1 8K',
      'moonshot',
      'chat',
      100,
      8192,
      false,
      true,
      true,
      'Pricing pending: current official Moonshot USD-normalized price has not been verified for this legacy fallback model.',
      0,
      0,
      0,
      0,
      90
    ),
    (
      'moonshot-v1-128k',
      'Moonshot V1 128K',
      'moonshot',
      'long_context',
      100,
      131072,
      false,
      true,
      true,
      'Pricing pending: current official Moonshot USD-normalized price has not been verified for this legacy selectable model.',
      0,
      0,
      0,
      0,
      100
    ),
    (
      'glm-4',
      'GLM-4',
      'zhipu',
      'chat',
      100,
      131072,
      false,
      true,
      true,
      'Pricing pending: current official Zhipu price is not yet verified in the catalog seed.',
      0,
      0,
      0,
      0,
      110
    ),
    (
      'glm-4-flash',
      'GLM-4 Flash',
      'zhipu',
      'chat',
      100,
      131072,
      false,
      true,
      true,
      'Pricing pending: current official Zhipu flash price is not yet verified in the catalog seed.',
      0,
      0,
      0,
      0,
      120
    ),
    (
      'qwen-max',
      'Qwen Max',
      'dashscope',
      'reasoning',
      100,
      262144,
      true,
      true,
      true,
      'Pricing pending: legacy selectable alias kept for compatibility; prefer Qwen3-Max where available.',
      0,
      0,
      0,
      0,
      130
    ),
    (
      'doubao-pro-32k',
      'Doubao Pro 32K',
      'volcengine',
      'chat',
      100,
      32768,
      false,
      true,
      true,
      'Pricing pending: legacy config alias does not map cleanly to the current official Ark model id.',
      0,
      0,
      0,
      0,
      140
    ),
    (
      'Doubao-pro-32k',
      'Doubao Pro 32K',
      'volcengine',
      'chat',
      100,
      32768,
      false,
      true,
      true,
      'Pricing pending: legacy frontend alias does not map cleanly to the current official Ark model id.',
      0,
      0,
      0,
      0,
      141
    ),
    (
      'doubao-pro-256k',
      'Doubao Pro 256K',
      'volcengine',
      'chat',
      100,
      262144,
      true,
      true,
      true,
      'Pricing pending: legacy selectable alias does not map cleanly to the current official Ark model id.',
      0,
      0,
      0,
      0,
      150
    ),
    (
      'Doubao-pro-256k',
      'Doubao Pro 256K',
      'volcengine',
      'chat',
      100,
      262144,
      true,
      true,
      true,
      'Pricing pending: legacy selectable alias does not map cleanly to the current official Ark model id.',
      0,
      0,
      0,
      0,
      151
    ),
    (
      'qiniu-llm',
      'Qiniu LLM',
      'qiniu',
      'proxy',
      100,
      4096,
      false,
      true,
      false,
      'Pricing pending: generic proxy placeholder model, kept for compatibility only.',
      0,
      0,
      0,
      0,
      160
    ),
    (
      'Qwen/Qwen2.5-72B-Instruct',
      'Qwen 2.5 72B Instruct',
      'siliconflow',
      'proxy',
      100,
      8192,
      false,
      true,
      false,
      'Pricing pending: current SiliconFlow USD-normalized price is not yet verified in the catalog seed.',
      0,
      0,
      0,
      0,
      170
    ),
    (
      'youyun-llm',
      'Youyun LLM',
      'youyun',
      'proxy',
      100,
      4096,
      false,
      true,
      false,
      'Pricing pending: generic proxy placeholder model, kept for compatibility only.',
      0,
      0,
      0,
      0,
      180
    )
)
INSERT INTO public.ai_models (
  id,
  name,
  provider,
  category,
  default_daily_limit,
  max_context_tokens,
  supports_thinking,
  is_enabled,
  is_visible,
  description,
  input_price,
  output_price,
  input_price_per_million,
  output_price_per_million,
  sort_order
)
SELECT
  id,
  name,
  provider,
  category,
  default_daily_limit,
  max_context_tokens,
  supports_thinking,
  is_enabled,
  is_visible,
  description,
  input_price,
  output_price,
  input_price_per_million,
  output_price_per_million,
  sort_order
FROM catalog
ON CONFLICT (id) DO UPDATE
SET
  name = EXCLUDED.name,
  provider = EXCLUDED.provider,
  category = EXCLUDED.category,
  default_daily_limit = EXCLUDED.default_daily_limit,
  max_context_tokens = EXCLUDED.max_context_tokens,
  supports_thinking = EXCLUDED.supports_thinking,
  description = EXCLUDED.description,
  input_price = EXCLUDED.input_price,
  output_price = EXCLUDED.output_price,
  input_price_per_million = EXCLUDED.input_price_per_million,
  output_price_per_million = EXCLUDED.output_price_per_million,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
